import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { Check,ArrowLeft } from 'lucide-react';
import { getSiteContent } from '@/lib/content';
import { Photo } from '@/components/photo';
import { Eyebrow,ButtonLink } from '@/components/ui';
type Props={params:Promise<{slug:string}>};
export async function generateStaticParams(){const {programs}=await getSiteContent();return programs.map(p=>({slug:p.slug}));}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const {programs}=await getSiteContent();const p=programs.find(p=>p.slug===slug);return {title:p?.title||'Program',description:p?.summary,alternates:{canonical:`/programs/${slug}`}};}
export default async function ProgramPage({params}:Props){const {slug}=await params;const {programs,settings}=await getSiteContent();const program=programs.find(p=>p.slug===slug);if(!program)notFound();return <><section className="shell py-14"><Link href="/programs" className="mb-12 inline-flex items-center gap-3 py-3 text-xs text-muted"><ArrowLeft size={15} aria-hidden/>All programs</Link><Eyebrow>{program.category}</Eyebrow><h1 className="display max-w-5xl">{program.title}</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-muted">{program.summary}</p></section><div className="shell"><Photo image={program.image} priority parallax caption className="h-[340px] rounded-[28px] md:h-[560px]" sizes="100vw"/></div><section className="shell grid gap-14 py-20 lg:grid-cols-[1.25fr_1fr]"><div><h2 className="text-4xl tracking-[-.045em]">{program.shortTitle}</h2><p className="mt-7 text-base leading-8 text-muted">{program.body}</p><h3 className="mt-10 text-lg font-semibold">What this program focuses on</h3><ul className="mt-6 space-y-5">{program.includes.map(v=><li key={v} className="flex items-start gap-3 text-sm leading-6"><Check size={17} className="mt-1 shrink-0 text-clay" aria-hidden/>{v}</li>)}</ul></div><aside className="h-fit rounded-3xl bg-linen p-8 lg:sticky lg:top-28"><Eyebrow>A starting point</Eyebrow><h2 className="text-3xl tracking-tight">Let’s talk about<br/><span className="font-serif text-[1.2em] italic text-clay">your next step.</span></h2><p className="mt-5 text-sm leading-7 text-muted">{settings.serviceNote}</p><ButtonLink href={`/get-help?need=${encodeURIComponent(program.supportType)}`} className="mt-7 w-full">Request support</ButtonLink><Link href="/contact" className="mt-5 block py-2 text-center text-xs underline">Have a general question?</Link></aside></section></>;}
