import {defineField,defineType} from 'sanity';

const requiredText=(name:string,title:string,description?:string)=>defineField({name,title,description,type:'string',validation:R=>R.required().max(240)});
const optionalText=(name:string,title:string)=>defineField({name,title,type:'string'});
const body=(name:string,title:string)=>defineField({name,title,type:'text',rows:5,validation:R=>R.max(12000)});
const slug=defineField({name:'slug',title:'Page address',type:'slug',options:{source:'title',maxLength:96},validation:R=>R.required()});
const url=(name:string,title:string)=>defineField({name,title,type:'url',validation:R=>R.uri({scheme:['https']})});
const photo=(name:string,title:string)=>defineField({name,title,type:'image',options:{hotspot:true},description:'Only upload images LOOP may legally publish. Do not identify a stock subject as a LOOP participant. Use Position below for the website crop.',fields:[
  defineField({name:'alt',title:'Describe the image for someone who cannot see it',type:'string',validation:R=>R.required().max(240)}),
  optionalText('credit','Photographer / permission credit'),url('creditUrl','Credit link'),
  defineField({name:'stock',title:'Illustrative stock (not a LOOP activity)',type:'boolean',initialValue:true}),
  defineField({name:'position',title:'Focal position',type:'string',initialValue:'50% 50%',description:'For example 50% 30%. Used directly by the website.',validation:R=>R.regex(/^(?:100|[0-9]{1,2})% (?:100|[0-9]{1,2})%$/)})
]});
const supportTypes=['Court support','Employment','Reentry services','Transportation','Housing support','Family support','Housing/resource referrals','Youth programs','Other'];
const check=(name:string,title:string,description:string)=>defineField({name,title,description,type:'boolean',initialValue:false});
const siteSettings=defineType({name:'siteSettings',title:'Website settings',type:'document',fields:[
  requiredText('heroTitle','Hero first line'),requiredText('heroEmphasis','Hero editorial line'),body('heroBody','Hero supporting sentence'),photo('heroImage','Hero photograph'),
  body('aboutBody','Who we are'),body('serviceNote','Availability note'),optionalText('contactEmail','Public contact email'),optionalText('contactPhone','Public contact phone'),url('donationUrl','Approved donation platform link'),optionalText('announcement','Optional header announcement'),url('instagram','Instagram'),url('facebook','Facebook'),url('linkedin','LinkedIn'),
  defineField({name:'privacyNotice',title:'Owner-approved privacy notice',description:'Replace the launch-review notice only after reviewing providers, retention, minors, contacts, and applicable obligations. Plain text; use blank lines for paragraphs.',type:'text',rows:14})
],preview:{prepare:()=>({title:'LOOP website settings'})}});
const program=defineType({name:'program',title:'Programs',type:'document',fields:[requiredText('title','Program name'),slug,optionalText('shortTitle','Short card title'),requiredText('category','Small category label'),body('summary','Summary'),body('body','Full description'),defineField({name:'includes',title:'What this program includes',type:'array',of:[{type:'string'}],validation:R=>R.max(12)}),photo('image','Program image'),defineField({name:'supportType',title:'Preselected support category',type:'string',options:{list:supportTypes},validation:R=>R.required()}),defineField({name:'order',title:'Sort order',type:'number',initialValue:10})],orderings:[{title:'Website order',name:'websiteOrder',by:[{field:'order',direction:'asc'}]}]});
const event=defineType({name:'event',title:'Events',type:'document',fields:[requiredText('title','Event title'),slug,body('description','What visitors should know'),defineField({name:'startsAt',title:'Start date and time',type:'datetime',validation:R=>R.required()}),defineField({name:'endsAt',title:'End date and time (optional)',type:'datetime',validation:R=>R.custom((value,context)=>!value||!context.document?.startsAt||new Date(value).getTime()>new Date(context.document.startsAt as string).getTime()||'End must be after start.')}),defineField({name:'timeZone',title:'Display timezone',type:'string',initialValue:'America/New_York',description:'IANA timezone, such as America/Chicago.',validation:R=>R.required().custom(value=>{try{new Intl.DateTimeFormat('en-US',{timeZone:value}).format();return true;}catch{return 'Enter a valid IANA timezone.';}})}),requiredText('location','Venue / meeting details'),requiredText('category','Event category'),url('registrationUrl','Registration link (optional)'),photo('image','Event image'),check('confirmed','This event is confirmed and may be listed publicly','Unconfirmed events never appear on the website. Publish after checking date, venue, capacity and registration.')]});
const impact=defineType({name:'impact',title:'Verified impact',type:'document',fields:[requiredText('label','Metric label'),defineField({name:'value',title:'Verified value',type:'number',validation:R=>R.required().min(0)}),requiredText('period','Reporting period'),requiredText('source','Public-readable source / methodology note','This note appears publicly. Never paste personal data or confidential internal links.'),check('approved','Approved for public reporting','Publish only after an authorized owner verifies the number and reporting period.')],preview:{select:{title:'label',subtitle:'period'}}});
const story=defineType({name:'story',title:'Community stories',type:'document',fields:[requiredText('title','Story title'),slug,body('excerpt','Short introduction'),body('body','Story'),photo('image','Image'),defineField({name:'publishedAt',title:'Publication date',type:'datetime',validation:R=>R.required()}),check('consentApproved','Publication permission verified','Confirm participant consent, image rights and guardian permission when applicable. Do not store private release forms in this public dataset.')]});
const location=defineType({name:'location',title:'Service locations',type:'document',fields:[requiredText('name','Community name'),defineField({name:'slug',title:'Page address',type:'slug',options:{source:'name'},validation:R=>R.required()}),body('description','Local support description'),requiredText('serviceArea','Actual area served'),optionalText('contactEmail','Local public email'),check('active','This location is operating','Future expansion is not an active service area.')]});
export const schemaTypes=[siteSettings,program,event,impact,story,location];
