import Link from 'next/link';
import { ArrowDown,ArrowUpRight,CalendarDays,HeartHandshake,HandHeart,Users,Compass } from 'lucide-react';
import { Photo } from '@/components/photo';
import { LoopMark } from '@/components/logo';
import { ButtonLink,Eyebrow,SectionHeading,TextLink,ClosingCTA,Flower } from '@/components/ui';
import { ProgramCard,ProgramRows } from '@/components/programs';
import { SupportFinder } from '@/components/support-finder';
import { getSiteContent } from '@/lib/content';
import { media } from '@/content/media';
import { eventDate } from '@/lib/utils';
export default async function Home(){
  const {settings,programs,events,impact}=await getSiteContent();
  const featured=['housing-support-stability','youth-entrepreneurship-education','family-support'].map(slug=>programs.find(p=>p.slug===slug)!).filter(Boolean);
  const upcoming=events.filter(e=>Date.parse(e.endsAt||e.startsAt)>=Date.now()).slice(0,3);
  return <>
    <section className="relative overflow-hidden pt-10 pb-8 md:pt-14" aria-labelledby="home-title">
      <div className="shell relative grid items-center gap-10 lg:min-h-[670px] lg:grid-cols-[1.04fr_1fr] lg:gap-0">
        <div className="relative z-10 pb-3 lg:py-10"><Eyebrow>People first. Possibility for everyone.</Eyebrow><h1 id="home-title" className="display max-w-[780px] lg:relative lg:z-20 lg:w-[125%]">{settings.heroTitle}<br/><span className="font-serif text-[1.18em] font-normal italic tracking-[-.04em] text-clay">{settings.heroEmphasis}</span></h1><p className="mt-8 max-w-[370px] text-base leading-7 text-muted md:text-lg md:leading-8">{settings.heroBody}</p><div className="mt-9 flex flex-wrap items-center gap-6"><ButtonLink href="/get-help">Find your next step</ButtonLink><Link href="/about" className="group inline-flex min-h-12 items-center gap-3 text-xs font-semibold">Meet LOOP<ArrowUpRight className="liquid group-hover:-translate-y-0.5" size={17} aria-hidden/></Link></div><div className="mt-12 flex items-center gap-3 text-xs text-muted"><span className="flex size-9 items-center justify-center rounded-full border border-line"><ArrowDown size={15} aria-hidden/></span>Stronger people. Stronger communities.</div></div>
        <div className="relative h-[440px] sm:h-[540px] lg:ml-[-22px] lg:h-[650px]"><Photo image={settings.heroImage} priority parallax caption className="h-full rounded-t-[180px] rounded-b-[24px] sm:rounded-t-[260px]" sizes="(max-width:1024px) 100vw, 55vw"/><div className="absolute bottom-12 -left-3 flex items-center gap-4 rounded-[18px] border border-white/70 bg-paper/95 px-5 py-4 shadow-lg shadow-ink/10 backdrop-blur-md md:-left-8"><LoopMark className="h-9 w-14 text-clay"/><div><p className="text-sm font-semibold">A shared way forward.</p><p className="mt-1 text-[11px] text-muted">Community. Access. Empowerment.</p></div></div><Flower className="absolute -top-4 right-0 size-20 text-clay md:size-24"/></div>
      </div>
      <svg className="hero-rings pointer-events-none absolute -bottom-[290px] -left-[170px] -z-10 size-[600px] text-clay/15" viewBox="0 0 600 600" fill="none" aria-hidden><circle cx="220" cy="300" r="210" stroke="currentColor"/><circle cx="380" cy="300" r="210" stroke="currentColor"/></svg>
    </section>
    <section aria-label="Ways to connect with LOOP" className="shell py-8"><div className="grid grid-cols-2 overflow-hidden rounded-2xl border border-line lg:grid-cols-4">{[{href:'/get-help',title:'I’m looking for support',sub:'Let’s find a starting point',Icon:Compass},{href:'/volunteer',title:'I’d like to volunteer',sub:'Give your time and talent',Icon:HandHeart},{href:'/partner',title:'Let’s work together',sub:'Build something meaningful',Icon:HeartHandshake},{href:'/donate',title:'I want to give',sub:'Help make more possible',Icon:Users}].map(({href,title,sub,Icon},i)=><Link href={href} key={href} className={`group liquid flex min-h-[136px] flex-col justify-between gap-5 border-line p-5 md:p-7 ${i>0?'border-l':''} ${i>1?'border-t lg:border-t-0':''} ${i===0?'bg-forest text-paper':'bg-paper hover:bg-linen'}`}><div className="flex items-center justify-between"><Icon size={22} strokeWidth={1.5} aria-hidden/><ArrowUpRight size={16} className="liquid group-hover:-translate-y-1 group-hover:translate-x-1" aria-hidden/></div><div><p className="text-sm font-semibold">{title}</p><p className={`mt-1.5 text-[11px] ${i===0?'text-paper/75':'text-muted'}`}>{sub}</p></div></Link>)}</div></section>
    <section className="shell py-20 md:py-28" aria-labelledby="mission-title"><div className="grid gap-9 md:grid-cols-[.55fr_1.45fr]"><Eyebrow>We are LOOP</Eyebrow><div data-reveal><h2 id="mission-title" className="section-title max-w-5xl">Life moves forward<br/>when <span className="font-serif text-[1.16em] italic text-clay">we move together.</span></h2><div className="mt-8 grid gap-7 lg:grid-cols-[1.2fr_1fr]"><p className="text-base leading-8 text-muted">{settings.aboutBody}</p><div className="lg:pl-10"><p className="mb-7 text-sm leading-7 text-muted">A place to be heard. A connection that opens a door. A practical next step. That’s where we begin.</p><TextLink href="/about">Our purpose, in practice</TextLink></div></div></div></div><div className="mt-16 grid grid-cols-[1fr_1.1fr_.8fr] items-center gap-3 md:gap-6"><Photo image={media.community} parallax className="h-48 rounded-2xl md:h-80" sizes="33vw"/><div className="relative" data-orbit><Photo image={media.hero} className="h-64 rounded-t-full rounded-b-2xl md:h-[430px]" sizes="40vw"/><span className="absolute -bottom-5 left-1/2 -translate-x-1/2 whitespace-nowrap rounded-full bg-peach px-4 py-3 font-serif text-xl italic text-clay md:px-6 md:text-2xl">Everyone belongs in the picture.</span></div><div><Flower className="mx-auto mb-6 size-14 text-clay md:size-24"/><Photo image={media.family} parallax className="h-36 rounded-2xl md:h-64" sizes="27vw"/></div></div><p className="mt-10 text-right text-[10px] text-muted">Illustrative stock imagery. Not photographs of LOOP participants.</p></section>
    <section data-dark className="overflow-hidden bg-forest py-20 text-paper md:py-28"><div className="shell"><div className="mb-12 flex flex-col justify-between gap-8 md:flex-row md:items-end"><SectionHeading eyebrow="Our programs" title="Pathways," emphasis="not barriers." light/><div className="max-w-sm"><p className="mb-5 text-sm leading-7 text-paper/75">Seven connected areas of support. One simple belief: everyone deserves the opportunity to move forward.</p><TextLink href="/programs">Explore every program</TextLink></div></div><div className="grid gap-5 md:grid-cols-4">{featured.map((p,i)=><ProgramCard key={p.slug} program={p} large={i===0}/>)}</div><div className="mt-7"><ProgramRows programs={programs.filter(p=>!featured.some(f=>f.slug===p.slug))} light/></div></div></section>
    <section className="soft-grid py-20 md:py-28"><div className="shell grid gap-14 lg:grid-cols-[1fr_1fr]"><div data-reveal><SectionHeading eyebrow="You don’t have to figure it out alone" title="A place to start." emphasis="A person to turn to."/><p className="mt-7 max-w-md text-base leading-8 text-muted">You can start small. Tell us what kind of support you’re looking for, and how it’s safe to reach you.</p><div className="mt-10 max-w-md space-y-6">{[['01','Start with what you need.','Choose one or more areas of support.'],['02','Share what you’re comfortable sharing.','A broad description and a safe way to contact you are enough.'],['03','Explore the next step, together.','LOOP can respond about options and availability.']].map(([n,t,d])=><div className="flex gap-5" key={n}><span className="flex size-10 shrink-0 items-center justify-center rounded-full border border-line text-xs">{n}</span><div><h3 className="text-sm font-semibold">{t}</h3><p className="mt-2 text-sm leading-6 text-muted">{d}</p></div></div>)}</div></div><div className="self-center"><SupportFinder/></div></div></section>
    <section className="relative flex min-h-[500px] items-center overflow-hidden bg-forest text-paper md:min-h-[680px]" data-dark><div className="absolute inset-0"><Photo image={media.hero} className="h-full w-full" parallax sizes="100vw"/></div><div className="absolute inset-0 bg-ink/65"/><div className="shell relative z-10 py-24 text-center"><p className="eyebrow mb-8 text-moss">Connection is where it begins</p><h2 className="text-[clamp(3.5rem,7.5vw,8.4rem)] leading-[.97] tracking-[-.065em]">The difference<br/>is <span className="font-serif text-[1.17em] italic text-peach">all of us.</span></h2><p className="mx-auto mt-8 max-w-md text-sm leading-7 text-paper/85">Every conversation, every connection, every person who shows up can be part of a shared way forward.</p><ButtonLink href="/volunteer" variant="light" className="mt-8">Find your place</ButtonLink></div><span className="absolute right-6 bottom-5 text-[10px] text-white/80">Illustrative stock photography</span></section>
    <section className="shell py-20 md:py-28"><div className="mb-12 flex flex-col justify-between gap-8 md:flex-row md:items-end"><SectionHeading eyebrow="Community in motion" title="Next up," emphasis="together."/><TextLink href="/events">See community events</TextLink></div>{upcoming.length?<div className="grid gap-6 md:grid-cols-3">{upcoming.map(event=><Link href={`/events/${event.slug}`} key={event.slug} className="rounded-2xl border border-line p-6"><p className="eyebrow text-clay">{event.category}</p><h3 className="mt-6 text-2xl tracking-tight">{event.title}</h3><p className="mt-4 text-sm text-muted">{eventDate(event.startsAt,event.timeZone)}</p><p className="mt-2 text-sm text-muted">{event.location}</p><ArrowUpRight className="mt-8" aria-hidden/></Link>)}</div>:<div className="grid overflow-hidden rounded-[24px] border border-line md:grid-cols-[1fr_1.1fr]"><div className="bg-linen p-8 md:p-12"><CalendarDays size={36} strokeWidth={1.25} className="mb-9 text-clay" aria-hidden/><h3 className="text-3xl leading-tight tracking-[-.04em]">Good things take<br/><span className="font-serif text-[1.25em] italic">people coming together.</span></h3><p className="mt-5 max-w-sm text-sm leading-7 text-muted">Confirmed dates will appear here. For now, explore ways to help shape what’s next.</p><TextLink href="/events" className="mt-6">Stay connected</TextLink></div><div className="divide-y divide-line bg-white/30">{[['Community resource events','Resources, connections, and shared possibilities.'],['Youth programs & workshops','Room for young people to explore their ideas.'],['Volunteer opportunities','Bring what you care about into the community.']].map(([t,d],i)=><Link key={t} href={i===2?'/volunteer':'/events'} className="group flex items-center justify-between gap-5 p-8 md:px-10 md:py-9"><div><p className="text-lg tracking-[-.025em]">{t}</p><p className="mt-3 text-xs leading-6 text-muted">{d}</p></div><ArrowUpRight size={21} className="shrink-0" aria-hidden/></Link>)}</div></div>}</section>
    <section className="border-t border-line bg-linen/60 py-16"><div className="shell grid gap-8 md:grid-cols-[.8fr_1.2fr]"><div><Eyebrow>Our impact</Eyebrow><h2 className="text-4xl tracking-[-.05em]">People before numbers.<br/><span className="font-serif text-[1.2em] italic text-clay">Progress worth sharing.</span></h2></div>{impact.length?<div className="grid grid-cols-2 gap-6">{impact.slice(0,4).map(m=><div key={m.label}><p className="text-5xl tracking-tight">{m.value.toLocaleString()}</p><p className="mt-2 text-sm">{m.label}</p><p className="mt-2 text-xs text-muted">{m.period} · {m.source}</p></div>)}</div>:<div className="max-w-lg self-center"><p className="text-sm leading-7 text-muted">As LOOP’s work grows, this space will share verified community updates and meaningful outcomes — with the people behind the numbers always at the center.</p><TextLink href="/impact" className="mt-5">How we’ll share our progress</TextLink></div>}</div></section>
    <ClosingCTA/>
  </>;
}
