import type { Program } from '@/lib/types';
import { media } from './media';
/** Program scope comes from LOOP Website Brief, pages 2–3. Additional copy is proposed editorial language. */
export const programs: Program[] = [
  {slug:'court-community-support', title:'Court & Community Support', shortTitle:'Someone in your corner.', category:'Guidance & connection', summary:'Court accompaniment, courthouse outreach, and resource navigation for individuals and families navigating the justice system.', body:'Finding your way through the justice system can bring unfamiliar questions and practical barriers. LOOP’s Court & Community Support program centers accompaniment, community outreach, and connections to resources. This is community support, not legal representation.', includes:['Court accompaniment','Courthouse and community outreach','Resource navigation','Connections for individuals and families'], image:media.connection, supportType:'Court support', order:1},
  {slug:'visitation-transportation', title:'Visitation Transportation', shortTitle:'Keep your connection.', category:'Family & connection', summary:'Helping reduce transportation barriers for families visiting incarcerated loved ones at prisons and county jails.', body:'Distance should not be the only thing that determines whether a family can stay connected. This program focuses on reducing practical transportation barriers around visits to incarcerated loved ones. Ask about available options; a request does not reserve a trip or confirm a facility visit.', includes:['Transportation resource navigation','Support planning a family visit','Connections to available trip options','Information about next steps'], image:media.journey, supportType:'Transportation', order:2},
  {slug:'housing-support-stability', title:'Housing Support & Stability', shortTitle:'Room to begin again.', category:'Housing & stability', summary:'Housing resource navigation, transitional housing support, referrals, and connections to safe and stable housing opportunities.', body:'A stable place to live can create space for everything that comes next. LOOP helps people navigate housing resources and explore referrals and support options. Housing placement, eligibility, availability, and financial assistance must be confirmed with the relevant program or provider.', includes:['Housing resource navigation','Transitional housing support','Housing referrals','Connections to safe and stable opportunities'], image:media.home, supportType:'Housing support', order:3},
  {slug:'reentry-support', title:'Reentry Support', shortTitle:'A next chapter. Together.', category:'Housing & stability', summary:'Employment, transportation, resources, and referrals to help justice-impacted individuals rebuild stability.', body:'Returning to a community involves more than a single step. LOOP connects justice-impacted individuals with practical resources across employment, transportation, referrals, and other supports needed to rebuild stability. Your request can begin with the area that matters most to you.', includes:['Employment resource connections','Transportation resources','Community referrals','Practical support for rebuilding stability'], image:media.connection, supportType:'Reentry services', order:4},
  {slug:'youth-entrepreneurship-education', title:'Youth Entrepreneurship & Education', shortTitle:'Big ideas start here.', category:'Youth & opportunity', summary:'Hands-on learning in entrepreneurship, financial literacy, leadership, teamwork, and career possibilities for middle and high school students.', body:'Young people deserve room to imagine what they can build. LOOP’s youth programming introduces middle and high school students to entrepreneurship, business development, financial literacy, leadership, teamwork, and possible career paths. Enrollment dates and program locations will be shared when confirmed.', includes:['Entrepreneurship and business development','Financial literacy','Leadership and teamwork','Career exploration'], image:media.youth, supportType:'Youth programs', order:5},
  {slug:'family-support', title:'Family Support', shortTitle:'Stronger, side by side.', category:'Family & connection', summary:'Resources, referrals, events, transportation, and community-based support for families impacted by incarceration and the justice system.', body:'When a loved one is navigating the justice system, the effects often reach the whole family. LOOP brings together practical resources, referrals, transportation connections, events, and community-based support. Share only the broad kind of support you are looking for.', includes:['Family resource connections','Referrals and navigation','Transportation connections','Community-based events and support'], image:media.family, supportType:'Family support', order:6},
  {slug:'community-outreach-events', title:'Community Outreach & Events', shortTitle:'Good things happen together.', category:'Guidance & connection', summary:'Resource events, care markets, youth forums, outreach campaigns, volunteer projects, and other grassroots initiatives.', body:'Community grows through showing up for one another. LOOP’s outreach program includes resource events, care markets, youth forums, volunteer projects, and grassroots initiatives. Confirmed dates and participation details appear on the events page as they become available.', includes:['Community resource events and care markets','Youth forums','Outreach campaigns','Volunteer projects and grassroots initiatives'], image:media.community, supportType:'Other', order:7}
];
