import type { Metadata } from 'next';
import Link from 'next/link';
import { getSiteContent } from '@/lib/content';
import { PageIntro } from '@/components/page-intro';
export const metadata:Metadata={title:'Privacy notice',robots:{index:false,follow:true}};
const sections=[
 ['Information you choose to share','When forms are activated, LOOP requests your name, a safe contact method, the contact details needed for that method, selected interests, optional city and state, and a short message. Partnership inquiries also request organization details. Please do not include Social Security numbers, case files, medical details, sensitive information about children, or anyone else’s contact information without permission.'],
 ['Where a request goes','Active forms deliver your information through Resend to an inbox designated by LOOP. Requests are not saved in the public website CMS. Email and provider systems can retain records; LOOP must approve its mailbox permissions, retention schedule, deletion procedure, and provider settings before launch. Do not treat this form as a confidential legal or medical channel.'],
 ['Contact preferences and email updates','The contact method you choose is included in the request to LOOP. Support, volunteer, partnership, and contact requests are not newsletter subscriptions. Email updates use a separate opt-in form and are delivered to LOOP for its approved mailing workflow. Ask LOOP to stop email updates using the published contact route.'],
 ['Security checks','When active in production, Cloudflare Turnstile checks form requests. A shared Upstash counter uses a salted hash of the request IP address, rather than the raw IP, to limit repeated submissions. The counter expires after ten minutes. Infrastructure providers may have their own access logs and retention policies.'],
 ['Website preferences and analytics','The optional motion preference is stored on your device. Form drafts are held only in the current page state; this application does not deliberately save them in browser storage. Analytics is off by default. If enabled, the application filters out support and inquiry routes and removes query strings and fragments before sending page views. No form values or custom form events are sent by this analytics integration.'],
 ['Images and external links','Some initial photographs are illustrative stock, not LOOP participants or evidence of LOOP activity. External donation and social links use the relevant provider’s own privacy practices. The website does not collect payment card information.'],
 ['Questions and requests','Use LOOP’s published contact details for privacy questions, corrections, deletion requests, or email-update preferences. An approved privacy contact and policy must be supplied before live forms are enabled. This draft is implementation guidance, not a final legal privacy policy.']
];
export default async function Privacy(){const {settings}=await getSiteContent();return <><PageIntro eyebrow={settings.privacyNotice?'Privacy':'Pre-launch draft · owner approval required'} title="Your information." emphasis="Your choice." description="Clear information about what this website collects and where it goes."/><article className="shell pb-24"><div className="max-w-3xl">{settings.privacyNotice?settings.privacyNotice.split('\n\n').map((p,i)=><p key={i} className="mb-6 text-base leading-8 text-muted">{p}</p>):sections.map(([t,d])=><section key={t} className="mb-10"><h2 className="text-2xl tracking-tight">{t}</h2><p className="mt-4 text-sm leading-8 text-muted">{d}</p></section>)}<Link href="/contact" className="inline-flex min-h-12 items-center rounded-full bg-ink px-7 py-3 text-sm text-paper">Contact LOOP</Link></div></article></>;}
